accounts/urls.py
from django.urls import path
from django.views.generic import TemplateView
from accounts.views import UserSignUp,UserSignIn,UserSignOut

urlpatterns = [    
    path('signin/',UserSignIn.as_view(), name='signin'),
    path('signup/',UserSignUp.as_view(), name='signup'),
    path('logout/',UserSignOut.as_view(), name='signout'),
]

redirector/urls.py
from django.urls import path
from redirector.views import urlRedirectCreate,urlRedirect,deleteUrl

app_name="redirector"
urlpatterns = [
    path('', urlRedirectCreate.as_view(), name='redirectcreate'),
    path('delete/<slug:urldelete>/', deleteUrl, name='deleteurl'),    
    path('<slug:urlto>/', urlRedirect, name='urlredirect'),    
]

urlredirect/urls.py
from redirector.views import urlRedirect
from django.contrib import admin
from django.urls import path,include
from redirector import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('redirector.urls', namespace="redirector")),
    #path('<slug:urlto>/', views.urlRedirect, name='urlredirect'),
    path('accounts/',include('accounts.urls')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser,BaseUserManager, PermissionsMixin

# Create your models here.

class UserProfileManager(BaseUserManager):
    #manager for user profiles

    def create_user(self, email, name, password=None):
        #create a new user profile
        if not email:
            raise ValueError('Email address must not be empty')

        email = self.normalize_email(email)
        user = self.model(email=email, name=name)

        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_superuser(self,email,name,password):
        # Create and save new super user with given details
        user = self.create_user(email,name,password)

        user.is_superuser = True
        user.is_staff = True

        user.save(using=self._db)

        return user


class UserProfile(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(max_length=100, unique=True,)
    name = models.CharField(max_length=50)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = UserProfileManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name']


    def get_full_name(self):
        #this appears alongside the username in an object’s history in admin
        return self.name

    def get_short_name(self):
        #this replaces the username in the greeting to the user in the header of admin
        return self.name

    def __str__(self):
        #returning the string representation of our user
        return self.email

redirector/models.py
from django.db import models
from django.conf import settings

# Create your models here.

class URLredirects(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
    url = models.URLField(max_length=300)
    urlhash = models.CharField(max_length=30)

    def __str__(self):
        return self.url

    class Meta:
        db_table = 'redirector'
        verbose_name = 'URL Redirect'

accounts/views.py
from django.shortcuts import redirect, render
from django.views import View
from django.contrib.auth.models import auth
from django.contrib.auth import get_user_model
from django.contrib import messages

User = get_user_model()

# Create your views here.

class UserSignUp(View):
    def get(self,request):
        return render(request,'signup.html')
    
    def post(self, request):
        email = request.POST['email']
        name = request.POST['name']
        password1 = request.POST['pass']
        password2 = request.POST['repass']

        if(password1 == password2):
            if(User.objects.filter(email=email).exists()):
                messages.error(request,'account already exist')
                return redirect('/accounts/signup/')
            else:
                user = User.objects.create_user(email=email, name=name, password=password1)
                user.save()
                return redirect('/')

        else:
            messages.error(request,'password not matching')
            return redirect('/accounts/signup/')


class UserSignIn(View):
    def get(self,request):
        return render(request,'signin.html')

    def post(self,request):
        email = request.POST['email']
        password = request.POST['pass']

        user = auth.authenticate(email=email, password=password)

        if(user is not None):
            auth.login(request,user)
            return redirect('/')
        else:
            messages.error(request,'invalid credentials')
            return redirect('/accounts/signin/')


class UserSignOut(View):
    def get(self,request):
        auth.logout(request)
        return redirect("/")

redirector/views.py
from django.shortcuts import redirect, render
from django.views import View
from redirector.models import URLredirects
from django.contrib import messages
import random,string
from urlredirect import settings

# Create your views here.

class urlRedirectCreate(View):

    def get(self,request):
        if request.user.is_authenticated:
            all_urls = URLredirects.objects.filter(user=request.user)
            domain = settings.urlhosting
            data = {
                'urls' : all_urls,
                'domain' : domain
            }
        else:
            data = {}
        return render(request,'home.html',{'data':data})

    
    def post(self,request):
        if (request.user.is_authenticated):
            url = request.POST['url']
            custname = request.POST['cust']
            new_hash=''

            if set(custname).difference(string.ascii_letters + string.digits):
                messages.info(request,'no special characters allowed')
                return redirect("/")

            if(URLredirects.objects.filter(user=request.user).filter(url=url).exists()):
                messages.info(request,'redirect already exist')
                return redirect("/")

            if(url[:5] == 'https'):
                url = url[8:]

            if (custname is not None):            
                if URLredirects.objects.filter(urlhash=custname).exists():                
                    messages.error(request,'Custom Name already taken')
                    return redirect("/")
                else:
                    new_hash = custname                

            if (custname == ''):
                new_hash = ''.join(random.choice(string.ascii_letters) for x in range(10))
                print("I was here********",new_hash)
                while (URLredirects.objects.filter(urlhash = new_hash).exists()):
                    new_hash = ''
                    new_hash = ''.join(random.choice(string.ascii_letters) for x in range(10))
                
            new_url = URLredirects(user=request.user,url=url, urlhash=new_hash)
            new_url.save()
            messages.info(request, 'URL shortened')
            return redirect('/')
        else:
            return redirect('/accounts/signin')


def deleteUrl(request,urldelete=None):
    URLredirects.objects.filter(urlhash=urldelete).delete()
    return redirect('/')


def urlRedirect(request, urlto=None):
    data = URLredirects.objects.get(urlhash=urlto)
    new_site = "https://"+data.url
    return redirect(new_site)

templates/home.html
{% extends 'navbar.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

</head>
<body>
{% block content %}

<section id="main">

    <div class="container-fluid">
        <div class="logo">
            <img src="{% static 'images/Capture.png' %}" alt="project-logo">
        </div>
        
        <div class="urlbar">
            <form class="g-3" action="{% url 'redirector:redirectcreate' %}" method="POST">   
                {% csrf_token %}                
                <div class="row">
                    <div class="col-auto">
                        <label for="urlinput" class="visually-hidden">URL</label>
                        <input type="text" class="form-control" name="url" id="urlinput" placeholder="URL (required)">
                    </div>
                 
                    <div class="col-auto">
                        <button type="submit" class="btn btn-light mb-3">Minify</button>
                    </div>
                </div>
                <div class="row justify-content-md-center" >
                    <div class="col-md-9 col-8" style="margin: auto;">
                        <label for="name" class="visually-hidden">custname</label>
                        <input type="text" class="form-control" name="cust" id="name" placeholder="custom (optional)">
                    </div>
                </div> 
            </form>            

        </div>       
        
    </div>

    <div class="starhr">
        <img src="{% static 'images/starhr.JPG' %}" height="10%" width="20%" alt="divider">
    </div>


</section>

<section id="urllist">
    <div class="container">

        <h2 class="text-uppercase text-center text-secondary">URLS</h2>

        <div class="starhrblack">
            <img src="{% static 'images/starhrblack.JPG' %}" height="10%" width="20%" alt="divider">            
        </div>
        
        {% if user.is_authenticated %}
        <div class="container"> 
            {% for url in data.urls %}                                    
                <div class="card" style="margin: 20px 0; border: solid#18bc9c">
                    <div class="card-header bg-transparent border-bottom-0">
                        <a href="{% url 'redirector:deleteurl' urldelete=url.urlhash %}"><button type="button" class="btn-close" aria-label="Close"></button></a>
                      </div>
                    <div class="card-body">
                        <p>Original Link : <a href="{% url 'redirector:urlredirect' urlto=url.urlhash %}" target="_blank">{{url.url}}</a></p>
                        <p>Redirected Link : <a href="{% url 'redirector:urlredirect' urlto=url.urlhash %}" target="_blank">{{data.domain}}/{{url.urlhash}}</a></p>
                    </div>
                </div>
            {% endfor %}            
        </div>
        {% endif %}
        
        <div class="starhrblack" style="padding-top: 6%;">
            <img src="{% static 'images/starhrblack.JPG' %}" height="10%" width="20%" alt="divider">            
        </div>
    </div>
</section>

{% if messages %}
    <script>        
        alert("{% for message in messages %}{{ message }}{% endfor %} ")
    </script>
{% endif %}


{% endblock %}
</body>
</html>

templates/navbar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/home.css' %}">

    <title>URL Redirector</title>
</head>
<body>

    <!---navbar--->
    <nav class="navbar navbar-expand-md navbar-dark bg-dark sticky-top">
        <div class="container-fluid">
            <span class="navbar-brand mb-0 h1">deurl</span>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
                <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <h5 class="nav-link text-light">Welcome!  {{user.name}}</h5>
                    </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href="#main">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="">About</a>
                    </li>

                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'signout' %}">Sign out</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'signin' %}">Sign In</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>  
    <!---navbar-->

    {% block content %}

    {% endblock %}

    
</body>
</html>

templates/signin.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.83.1">
    <title>Sign In</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/sign-in/">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/signin.css' %}">

</head>

<body>
    <div class="container text-center body-css">

        <main class="form-signin">
            <form action="{% url 'signin' %}" method="POST">
                
                {% csrf_token %}
                
                <img class="mb-4" src="{% static 'images/Capture.png' %}" alt="" width="72" height="72">
                <h1 class="h3 mb-3 fw-normal" style="color: white !important;">Please sign in</h1>          

                <div class="form-floating">
                    <input type="email" class="form-control" name="email" id="floatingInput" placeholder="name@example.com">
                    <label for="floatingInput">Email address</label>
                </div>
                <div class="form-floating">
                    <input type="password" class="form-control" name="pass" id="floatingPassword" placeholder="Password">
                    <label for="floatingPassword">Password</label>
                </div>
                <button class="w-100 btn btn-lg btn-dark mt-4" type="submit">Sign in</button>
                <p class="mt-5 mb-3 text-dark" style="font-size: large;">Don't have a account? <a href="{% url 'signup' %}">sign up</a></p>
                <p class="mt-5 mb-3 text-muted">&copy; 2017–2021</p>
            </form>
        </main>
    </div>

    {% if messages %}
    <script>        
        alert("{% for message in messages %}{{ message }}{% endfor %} ")
    </script>
    {% endif %}


</body>

</html>

templates/signup.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.83.1">
    <title>Sign Up</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/sign-in/">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/signup.css' %}">

</head>

<body>
    <div class="container text-center body-css">

        <main class="form-signin">
            <form action="{% url 'signup' %}" method="POST">

                
                {% csrf_token %}
                
                <img class="mb-4" src="{% static 'images/Capture.png' %}" alt="" width="72" height="72">
                <h1 class="h3 mb-3 fw-normal" style="color: white !important;">Please sign in</h1>
                
                <div class="form-floating">
                    <input type="text" class="form-control" name="name" id="floatingName" placeholder="name@example.com">
                    <label for="floatingName">Name</label>
                </div>
                <div class="form-floating">
                    <input type="email" class="form-control" name="email" id="floatingInput" placeholder="name@example.com">
                    <label for="floatingInput">Email address</label>
                </div>
                <div class="form-floating">
                    <input type="password" class="form-control pass" name="pass" id="floatingPaasword" placeholder="name@example.com">
                    <label for="floatingPassword">Password</label>
                </div>
                <div class="form-floating">
                    <input type="password" class="form-control repass" name="repass" id="floatingPasswordConfirm" placeholder="Password">
                    <label for="floatingPasswordConfirm">Re-enter Password</label>
                </div>
                <button class="w-100 btn btn-lg btn-dark mt-4" type="submit">Sign in</button>
                <p class="mt-5 mb-3 text-dark" style="font-size: large;">Have an account? <a href="{% url 'signin' %}">sign in</a></p>
                <p class="mt-5 mb-3 text-muted">&copy; 2017–2021</p>
            </form>
        </main>
    </div>

    {% if messages %}
    <script>        
        alert("{% for message in messages %}{{ message }}{% endfor %} ")
    </script>
    {% endif %}

</body>

</html>